# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e403592eaecd16318c8600fd965be46c1cbbba98f43f330e6a138ac9bab3ec9d07f78822878501926883b3291259ff2fbd478531d014a0abb45f37d63ec459

test:
  secret_key_base: b44c0c1f5a63e3f96fb5720e3163cdf8fd9a128ba81198e4d73342e3ef67715c510165463108da174b90763dd68abe3d68db3c3458764d2f074d8dc78a8c6bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
